[package]
name = "paneerlang"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.99"
clap = { version = "4.5.47", features = ["derive"] }
colored = "3.0.0"
logos = "0.15.1"
rand = "0.9.2"
regex = "1.11.2"
